import { test, expect } from '@playwright/test'

test('each module renders and supports a basic answer flow', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await expect(page.getByRole('heading', { name: 'NoteSense 音感训练器' })).toBeVisible()

  await page.getByRole('button', { name: 'do' }).click()
  await expect(page.getByRole('status')).toBeVisible()

  await page.getByRole('button', { name: '单音听辨' }).click()
  await expect(page.getByTestId('module-single-note')).toBeVisible()
  await page.getByRole('button', { name: 'C' }).click()
  await expect(page.getByRole('status')).toBeVisible()

  await page.getByRole('button', { name: '旋律短句听写' }).click()
  const melodyModule = page.getByTestId('module-melody')
  await expect(melodyModule).toBeVisible()
  await melodyModule.locator('.option-grid button', { hasText: 'C' }).click()
  await melodyModule.locator('.option-grid button', { hasText: 'D' }).click()
  await melodyModule.locator('.option-grid button', { hasText: 'E' }).click()
  await page.getByRole('button', { name: '提交' }).click()
  await expect(page.getByRole('status')).toBeVisible()

  await page.getByRole('button', { name: '和弦性质听辨' }).click()
  await expect(page.getByTestId('module-chord')).toBeVisible()
  await page.getByTestId('module-chord').locator('.option-grid button').first().click()
  await expect(page.getByRole('status')).toBeVisible()

  await page.getByRole('button', { name: '根音冠音音程速算' }).click()
  await expect(page.getByTestId('module-interval')).toBeVisible()
  await expect(page.getByText('音量')).toHaveCount(0)
  const intervalModule = page.getByTestId('module-interval')
  await intervalModule.getByRole('button', { name: 'C' }).click()
  await intervalModule.getByRole('button', { name: '♮' }).click()
  await expect(page.getByRole('status')).toBeVisible()
  await page.getByRole('button', { name: '根音冠音音程速算' }).click()
  await page.getByRole('button', { name: '算音程' }).click()
  await expect(intervalModule.getByRole('button', { name: '8度' })).toHaveCount(0)
  await intervalModule.getByRole('button', { name: '3度' }).click()
  await intervalModule.getByRole('button', { name: '大' }).click()
  await expect(page.getByRole('status')).toBeVisible()
  await page.getByRole('button', { name: '混合' }).click()
  await expect(page.getByTestId('module-interval')).toBeVisible()

  await page.getByRole('button', { name: '切分节奏跟拍' }).click()
  const syncopationModule = page.getByTestId('module-syncopation')
  await expect(syncopationModule).toBeVisible()
  await expect(page.getByText('音量')).toHaveCount(0)
  await expect(syncopationModule.getByRole('button', { name: '四分稳拍' })).toHaveCount(0)
  await expect(syncopationModule.getByRole('button', { name: '八分稳拍' })).toHaveCount(0)
  await expect(syncopationModule.getByRole('button', { name: '八分反拍' })).toHaveClass(/active/)
  await expect(syncopationModule.getByRole('button', { name: '正反拍混合' })).toBeVisible()
  await expect(syncopationModule.getByRole('button', { name: '十六分切分' })).toBeVisible()
  await expect(syncopationModule.getByRole('button', { name: '附点训练' })).toBeVisible()
  await expect(syncopationModule.getByRole('button', { name: '跨拍连音' })).toBeVisible()
  await expect(syncopationModule.getByText('使用空格可能会有约 140ms 的延迟')).toBeVisible()
  await syncopationModule.getByLabel('输入校准').fill('-100')
  await expect(syncopationModule.getByLabel('简谱节奏型')).toBeVisible()
  await syncopationModule.getByRole('button', { name: '正确节奏' }).click()
  await expect(syncopationModule.locator('.rhythm-cell.demo-active').first()).toBeVisible({ timeout: 5000 })
  await expect(syncopationModule.getByRole('button', { name: '拍', exact: true })).toBeDisabled()
  await page.waitForTimeout(2500)
  await syncopationModule.getByRole('button', { name: '附点训练' }).click()
  await syncopationModule.getByRole('button', { name: '100 bpm' }).click()
  await syncopationModule.getByRole('button', { name: '五线谱节奏' }).click()
  await expect(syncopationModule.getByLabel('五线谱节奏型')).toBeVisible()
  await syncopationModule.getByRole('button', { name: '开始', exact: true }).click()
  await page.waitForTimeout(2500)
  await page.keyboard.press('Space')
  await syncopationModule.getByRole('button', { name: '拍', exact: true }).click()
  await expect(page.getByRole('status')).toBeVisible({ timeout: 6000 })
  const answeredBeforeReplay = await syncopationModule.locator('.stats-row').getByText(/已答 \d+/).textContent()
  await expect(syncopationModule.getByRole('button', { name: '回放我的节奏' })).toBeVisible()
  await expect(syncopationModule.getByRole('button', { name: '对比标准' })).toBeVisible()
  await syncopationModule.getByRole('button', { name: '回放我的节奏' }).click()
  await expect(syncopationModule.locator('.rhythm-cell.user-active').first()).toBeVisible({ timeout: 5000 })
  await expect(syncopationModule.getByRole('button', { name: '下一题' }).first()).toBeDisabled()
  await page.waitForTimeout(2500)
  await expect(syncopationModule.locator('.stats-row').getByText(answeredBeforeReplay ?? '')).toBeVisible()
  await syncopationModule.getByRole('button', { name: '对比标准' }).click()
  await expect(syncopationModule.locator('.rhythm-cell.standard-active').first()).toBeVisible({ timeout: 5000 })

  await page.getByRole('button', { name: '调内级数和弦' }).click()
  const degreeModule = page.getByTestId('module-degree-chord')
  await expect(degreeModule).toBeVisible()
  await expect(page.getByText('音量')).toHaveCount(0)
  await degreeModule.getByRole('button', { name: 'C' }).click()
  await degreeModule.getByRole('button', { name: '♮' }).click()
  await degreeModule.getByRole('button', { name: /大三|小三|减三/ }).first().click()
  await degreeModule.getByRole('button', { name: '提交' }).click()
  await expect(page.getByRole('status')).toBeVisible()

  await page.getByRole('button', { name: '和弦所属大调' }).click()
  const triadModule = page.getByTestId('module-triad-key-match')
  await expect(triadModule).toBeVisible()
  await expect(page.getByText('音量')).toHaveCount(0)
  await triadModule.getByRole('button', { name: '无符合大调' }).click()
  await triadModule.getByRole('button', { name: '提交' }).click()
  await expect(page.getByRole('status')).toBeVisible()
})

test('layout fits mobile width', async ({ page }) => {
  await page.goto('/')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: 'NoteSense 音感训练器' })).toBeVisible()
  await expect(page.locator('.trainer-surface')).toBeVisible()
})
